### ISSUE TITLE
Find way to replace all occurrence data records from lu_sgcnXpu without deleting modeled data

### ISSUE THREAD

**Issue by memoore** [PNHP/COA_Tools#31]
Currently, the tool replaces all 'K' occurrences with the update. However, this means that duplicate occurrence records labeled 'L' or 'U' would be added every time occurrence data are updated. Example, older fish records will be duplicated every time the data are updated.

**Comment by ChristopherTracey** [comment]
There are currently no fish models the tool and only fish records have that special use case applied, so for now one could delete the records that have an ELSeason code that begins with "AF" and OccProb="L".

**Comment by memoore** [comment]
I wrote in a line that does this, but we should probably establish infrastructure so we can handle models for all taxa in the future. 

Perhaps just another column in sgcnXpu designating whether the record is from a modeled or occurrence source?

**Comment by ChristopherTracey** [comment]
I would like to look at the models during the next data update (_provided we survive this one_), especially as we have additional models coming in from MoBI and I think we need to update thresholds for the existing models.  We should explore this then as well.

While adding a column to track this, its another column in a ~47million+ row table, which could be a significant amount of data to handle.

**Comment by memoore** [comment]
Duplicate issue. Closing this one.
