### ISSUE TITLE
Additional checks against lu_sgcn

### ISSUE THREAD

**Issue by ChristopherTracey** [PNHP/COA_Tools#33]
I think we need to add a series of additional checks against lu_sgcn in the set of scripts that load the general COA data.  This should happen in:
- 3_ActionsCleanup.r 
- 4_habitats.r

This will probably trigger some changes in where and how we load '00_PathsAndSettings.r' (currently only in the SGCN subfolder).

**Comment by memoore** [comment]
This is currently happening.
