### ISSUE TITLE
Blank ELSeason and OccProb values in lu_sgcnXpu table

### ISSUE THREAD

**Issue by memoore** [PNHP/COA_Tools#34]
Currently added line to exclude from the final lu_sgcnXpu table, 
BUT we need to add QC check for blank ELSeason and OccProb values in lu_sgcnXpu table and way to figure out where they are coming from and if it is a bigger problem.

**Comment by ChristopherTracey** [comment]
I think some of this was coming in from the Biotics and CPP scripts as they were originally written to match on SNAME and not ELCODE, and thus blank values would show up if the ELCODE/ELSeason was different.
