### ISSUE TITLE
Several SGCN final spatial datasets with missing fields

### ISSUE THREAD

**Issue by memoore** [PNHP/COA_Tools#38]
I tried to fix these ad hoc as I was going through the scripts by adding them in. But, we should double check and make sure the scripts are adding all necessary fields and standardize across all scripts.

**Comment by ChristopherTracey** [comment]
So the the CPP one of these was due to `final_cppCore_sf ` and `cppCore_sf_final` as names, and we were jumping back forth between them.  The former was the one we wanted.  @ChristopherTracey should write cleaner code...

**Comment by ChristopherTracey** [comment]
The bamona script was largely due to bad capitalization on `useCOA` and duplicate joins for `SeasonCode`.  Should be fixed now.

**Comment by ChristopherTracey** [comment]
Grouse script had issues with `SeasonCode`

**Comment by memoore** [comment]
I think these are all better now.
