### ISSUE TITLE
SGCN summary for tool website

### ISSUE THREAD

**Issue by ChristopherTracey** [PNHP/COA_Tools#47]
Possibly rewrite so Cathy doesn't have to rearrange manually.

**Comment by ChristopherTracey** [comment]
Took care of some of the field name changes.  Adding the header information (description/source key) manually.  This would be a good place to have dataset citations, which we do have one for BAMONA.  Leaving to this open so we can solve that.

**Comment by memoore** [comment]
This has been updated to include header information and field name changes. Open a different issue with dataset citations if needed.
