### ISSUE TITLE
Change Occurrence probabilities

### ISSUE THREAD

**Issue by ChristopherTracey** [PNHP/COA_Tools#5]
Confirmed = Known
Probable = Likely
Low = Unknown

**Comment by ChristopherTracey** [comment]
Need to fix a few things where upcase and lowcase versions of this codes exist.

**Comment by ChristopherTracey** [comment]
I think this has been largely cleared, but this may make an additional QC test we should add. @memoore

**Comment by memoore** [comment]
This has been working fine.
