### ISSUE TITLE
Range Maps - make modifications to the sws script

### ISSUE THREAD

**Issue by ChristopherTracey** [PNHP/COA_Tools#52]
Per Cathy's email

> **NOTE: Please modify the displayed attributes for the All Taxa and individual species layers to include:
•	Layer
•	Sub-Layer
•	County Name
•	Taxonomic Group
•	Common Name
•	Scientific Name
•	Breeding Species of Greatest Conservation Need (yes, null)
•	Migratory Species of Greatest Conservation Need (yes, null)
•	Wintering Species of Greatest Conservation Need (yes, null)
•	Year-round Species of Greatest Conservation Need (yes, null)
•	Global Rank
•	State Rank
•	Federal Status – NOTE – include ‘null’ rather than a blank.
•	State Status - NOTE – include ‘null’ rather than a blank.
•	Pennsylvania Biological Survey Status
DO NOT include the proportions for the SGCNs.

**Comment by memoore** [comment]
This is currently how the scripts are set up. Field aliases can be changed if needed, but reorganization of fields needs to happen at the FC level.
