### ISSUE TITLE
Range Maps - modify py script to alphabeticalize species while running

### ISSUE THREAD

**Issue by ChristopherTracey** [PNHP/COA_Tools#55]

**Comment by memoore** [comment]
If I understand this request correctly, it is now doing this. For example, it now runs like this:
_county_SGCN 1/524
county_AAAAA01050 2/524
county_AAAAA01060 3/524
county_AAAAA01100 4/524
county_AAAAC01011 5/524
county_AAAAD01010 6/524
county_AAAAD13014 7/524
county_AAAAE01042 8/524
county_AAABB01210 9/524
county_AAABC01030 10/524
...
etc.
