### ISSUE TITLE
increase reporting in the species populator script

### ISSUE THREAD

**Issue by ChristopherTracey** [PNHP/COA_Tools#65]
@memoore, would it be possible to increase the progress reporting in the [species populator script](https://github.com/PNHP/COA_Tools/blob/master/scripts/COA_species_populator%20v.5%20table%20dissolve%20Occurrence.py)? Two ideas that come to mind:

1. The script doesn't do much reporting after it finishes the last county (York).  Could we add something to say all county merges are complete and its moving on to joining/formatting all the files.
2. For each county, could we add some sort of progress saying its doing something.  For this past run, the counties have ranged from 8 minutes to 5 hours.  It would be great if we can know its not locked.  Maybe something like processing feature X of Y?

Let me know what you think.  Not a high priority as this update is progressing but it might be great for July!

**Comment by memoore** [comment]
Yep, we can do this!

**Comment by ChristopherTracey** [comment]
Thanks! Let me know if I can help!

**Comment by memoore** [comment]
This script was reformatted/reworked and no longer breaks into counties. It should have sufficient reporting and runs a bit more quickly now.
