### ISSUE TITLE
from michele: missing index

### ISSUE THREAD

**Issue by ChristopherTracey** [PNHP/COA_Tools#72]
Missing index applied for lu_sgcnXpu_all : CREATE INDEX maindex ON lu_sgcnXpu_all (unique_id, ELSeason).  Need to do this automatically so we don't forget

**Comment by memoore** [comment]
This was occurring because of later error checking and reformatting/resaving of the lu_sgcnXpu_all table. Rearranged scripts so that indexes are the final script run and this should solve the issue.
