### ISSUE TITLE
Range Maps - sort order

### ISSUE THREAD

**Issue by ChristopherTracey** [PNHP/COA_Tools#81]
Cathy and Diana would like us to change the species sort order to sort by the ELCODE in the county/huc range maps so that similar species group together (e.g. all the warblers, all the ducks).  

@memoore, I suspect we need to do this in the python script.  Can you give this a shot?

**Comment by memoore** [comment]
Current version sorts layers by ELCODE within groups. The layer under 'All Taxa Groups' will need to be manually updated to 'All Taxa' as it currently changes the name of the layer to whichever SCOMNAME is last in the table. I will work on fixing this later.

**Comment by ChristopherTracey** [comment]
Alright. I’ll start the update this week. Thanks!

**Comment by memoore** [comment]
This should be fixed now as well. No manual updates necessary outside of the collapsing of the layers/groups.
