### ISSUE TITLE
unmatched ELCODEs due to changes by NS

### ISSUE THREAD

**Issue by ChristopherTracey** [PNHP/COA_Tools#83]
Issues with the following species not matching up to Biotics:

- Aneides aeneus               
- Pseudacris brachyphona       
- Lota lota pop. 3             
- Agkistrodon contortrix       
- Ephemerella inconstans      
- Ephemerella floripara
- Bombus ashtoni               
- Callophrys gryneus           
- Metarranthis sp. near duaria 
- Chytonix sensilis           
- Chaetaglaea tremula
- Sympetrum internum           
- Lampsilis radiata            
- Quadrula pustulosa           
- Vertigo ventricosa          
- Appalachina sayana
- Triodopsis juxtidens
- Geolycosa turricola          
- Arachosia cubana

**Comment by memoore** [comment]
Pretty sure all these have now been updated in lu_sgcn and ancillary tables - changes reported to Cathy and Diana to fix in their WAPDATA.xlsx spreadsheet.
