### ISSUE TITLE
Add Dissolve step to 

### ISSUE THREAD

**Issue by ChristopherTracey** [PNHP/COA_Tools#87]
Hey @memoore.
  Can you look at the feasibility of adding a dissolve step to the 10_COA_species_populator v.5 table dissolve Occurrence.py script. This is currently a manual step that I run before running that script. There's no reason that this needs to be done manually and it would be good to run it as part of the script.  Here's a snippet of python exported from the command that I ran to do the dissolve:

`arcpy.analysis.PairwiseDissolve("allSGCNuse", r"D:\COA_Tools\_data\output\_update2022q1\SGCN.gdb\allSGCNuse_PairwiseDissolve", "ELSeason;OccProb", None, "MULTI_PART")`

Thanks!
-Chris

**Comment by memoore** [comment]
Updated script 10 to include dissolve, removed county loop because no longer needed.
